<?php
// This file is not called from WordPress. We don't like that.
! defined( 'ABSPATH' ) and exit;

/**
 **********************************************************************************************************
 * 												DO NOT EDIT THIS FILE
 **********************************************************************************************************
 * Theme functions
 *
 * @author		Yeahthemes
 * @copyright	Copyright ( c ) Yeahthemes
 * @link		http://yeahthemes.com
 * @since		Version 1.0
 * @package 	Yeah Includes
 */

//print_r($GLOBALS['yt_data']);


/**
 * Jetpack infinite scroll
 *
 * @since 1.0
 */

/**
 * Banner
 *
 * @since 1.0
 */

add_action( 'yt_header_start', 'yt_site_top_bar', 5 );

function yt_site_top_bar(){

	if( 'hide' == yt_get_options( 'header_top_bar_menu' ) )
		return;
	?>

		<div class="site-top-menu hidden-xs hidden-sm" id="site-top-menu">
			<div class="container">
				<div class="row">
					<div class="col-md-6 site-top-menu-left">
						<?php do_action( 'yt_site_left_top_bar' );?>
						

						<?php if( 'top_menu' === yt_get_options( 'header_social_links_position' ) ):?>
						<div class="site-social-networks">
							<?php yt_site_social_networks( false );?>
						</div>
						<?php endif?>
					</div>

					<div class="col-md-6 site-top-menu-right text-right">
						<?php do_action( 'yt_site_right_top_bar' );?>
						<?php
						if ( has_nav_menu( 'top' ) ) {
							$top_menu = wp_nav_menu(
								apply_filters( 'yt_site_top_menu_navigation_args', array( 
									'theme_location' => 'top' , 
									'echo' => false, 
									'container_class' => 'site-top-navigation-menu-container',
									'menu_class'      => 'menu list-inline',
									'items_wrap'      => '<ul id="%1$s" class="%2$s">%3$s</ul>',
									'depth' => 1,
								))
							);

							echo $top_menu;
						}


						?>

					</div>
				</div>
			</div>
		</div>
	<?php
}
//echo yt_get_social_network_counts('facebook','Yeahthemes') . '.' . yt_get_social_network_counts('twitter','Yeahthemes') . '.' . yt_get_social_network_counts('youtube','Yeahthemes');

if ( ! function_exists( 'yt_site_start_header_banner' ) ) {
	
	function yt_site_start_header_banner(){

		echo apply_filters( 'yt_site_start_header_banner',
		'<div class="site-banner" id="site-banner">
			<div class="container">
				<div class="row">' );
	}
}


if ( ! function_exists( 'yt_site_end_header_banner' ) ) {
	
	function yt_site_end_header_banner(){
		echo apply_filters( 'yt_site_end_header_banner',
				'</div>
			</div>
		</div>' );
	}
}
		
/**
 * Branding
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_branding' ) ) {
	
	function yt_site_branding(){
		
		/**
		 * Retrieve Options data
		 */
		$heading = is_home() ? 'h1' : 'h3';
		

		//Branding
		$branding = '<div class="col-md-2 site-branding pull-left">
			<'.$heading.' class="site-logo plain-text-logo"><a href="' . esc_url( home_url( '/' ) ) . '" title="' . esc_attr( yt_get_options('plain_logo_text') ) . '" rel="home">' . yt_get_options('plain_logo_text') . '</a></'.$heading.'>
		</div>';
		
		if( !yt_get_options('plain_logo') && yt_get_options('logo') ){
			$branding = '<div class="col-md-2 site-branding pull-left">
				<'.$heading.' class="site-logo image-logo"><a href="' . esc_url( home_url( '/' ) ) . '" title="' . esc_attr( yt_get_options('plain_logo_text') ) . '" rel="home"><img src="'. esc_url( yt_get_options('logo') ) .'">' . '</a></'.$heading.'>
			</div>';
		}
		
		echo $branding;
		
	}
}

/**
 * Primary Nav
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_primary_nav' ) ) {
	 
	function yt_site_primary_nav(){
		
		//Navnav
		if ( has_nav_menu( 'primary' ) ) {
			$primary_menu = wp_nav_menu(
				apply_filters( 'yt_site_primary_navigation_args', array( 
					'theme_location' => 'primary' , 
					'echo' => false, 
					'container_class' => 'site-navigation-menu-container',
					'menu_class'      => 'menu',
					'depth' => 5,
					'walker' => new YT_Walker_Nav_Mega_Menu_By_Category()
				))
			);
		}else{
			$primary_menu = '<ul class="menu"><li>' . sprintf( __('Create a Menu in <a href="%s">Menus</a> and assign it as Primary Menu in <a href="%s">Theme Location</a>', 'yeahthemes'), admin_url('nav-menus.php'), admin_url('nav-menus.php?action=locations') ) . '</li></ul>';
		}
		
		$site_navigaton = '<nav id="site-navigation" class="col-sm-12 col-md-10 main-navigation" role="navigation">
			<div class="sr-only skip-link"><a href="#content" title="' . esc_attr( 'Skip to content', 'yeahthemes' ) . '">' . __( 'Skip to content', 'yeahthemes' ) . '</a></div>

			' . $primary_menu . '
		</nav><!-- #site-navigation -->';
		
		//Allow editing site
		$site_navigaton = yt_apply_atomic( 'site_primary_menu', $site_navigaton );
		
		echo $site_navigaton;
	}
}
/**
 * Menu icon class
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_nav_menu_description_icon' ) ) {
	function yt_site_nav_menu_description_icon ( $array = array(), $atts ) {
		
		/*$array['parent'] = !empty( $atts['description'] ) ? $atts['description'] : '';
		$array['children'] = !empty( $atts['description'] ) ? $atts['description'] : '';*/
		$array['before'] = !empty( $atts['description'] ) ? '<i class="' . esc_attr( $atts['description'] ) . '">' : '';
		$array['after'] = !empty( $atts['description'] ) ? '</i>' : '';
		
		
		return $array;
		
	}
}
/**
 * Custom Menu item: Search
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_custom_menu_item' ) ) {
	function yt_site_custom_menu_item ( $items, $args ) {
		
		/*$items = '<li class="menu-item menu-item-type-custom menu-item-social-networks mega-menu-parent">
			<a href="#"><i class="fa fa-reorder"></i> Menu</a>
			<div class="mega-menu-content-wrapper full-width-wrapper">
				<div class="container">
					<ul class="sub-menu">
						<li id="menu-item-517" class="menu-item"><a href="http://192.168.1.15/framework/category/uncategorized/">Uncategorized</a></li>
						<li id="menu-item-518" class="menu-item"><a href="http://192.168.1.15/framework/category/audio/">Audio</a></li>
						<li id="menu-item-519" class="menu-item"><a href="http://192.168.1.15/framework/category/link/">Link</a></li>
						<li id="menu-item-520" class="menu-item"><a href="http://192.168.1.15/framework/category/link/video/">Video</a></li>
						<li id="menu-item-521" class="menu-item"><a href="http://192.168.1.15/framework/category/link/video/hello-x/">Hello</a></li>
						<li id="menu-item-522" class="menu-item"><a href="">Image</a></li>
					</ul>
				</div>
			</div>
		</li>';*/
		if( $args->theme_location == 'primary' ){

		  	$items = '<li class="site-mobile-menu-toggle hidden-md hidden-lg">
					<span><i class="fa fa-reorder open-menu"></i><i class="fa fa-times close-menu"></i></span>
				</li>
				<li class="site-mobile-menu-logo hidden-md hidden-lg site-logo">
					<a href="' . esc_url( home_url( '/' ) ) . '" title="' . esc_attr( yt_get_options('plain_logo_text') ) . '" rel="home">' . ( !yt_get_options( 'plain_logo' ) && yt_get_options('logo') ? '<img src="'. esc_url( yt_get_options('logo') ) .'">' : yt_get_options('plain_logo_text') )  . '</a>
				</li>' . $items;

	      	$items .= '<li class="menu-item menu-item-type-custom menu-item-gsearch default-dropdown sub-menu-left  pull-right">
				<a href="#"><i class="fa fa-search"></i></a>
				<ul class="sub-menu">
					<li class="menu-item">
						' . get_search_form( false ) . '
					</li>
				</ul>
			</li>';

			if( 'main_menu' === yt_get_options( 'header_social_links_position' ) ):

				$items .= '<li class="menu-item-type-custom menu-item-social-networks">' . yt_site_social_networks() . '</li>';

			endif;
		}elseif( $args->theme_location == 'mobile' ){
			$items = '<li class="menu-item-mobile-menu-logo">
					<a href="' . esc_url( home_url( '/' ) ) . '" title="' . esc_attr( yt_get_options('plain_logo_text') ) . '" rel="home"><img src="'. esc_url( yt_get_options('logo') ) .'">' . '</a>
				</li>' . $items;

			$items .= '<li class="menu-item-type-custom menu-item-social-networks">' . yt_site_social_networks() . '</li>';
		}
   
   		return $items;
   	}
}

/**
 * Ajax News Mega menu
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_ajax_mega_menu_by_category' ) ) {
	
	function yt_site_ajax_mega_menu_by_category( ){

		$nonce = isset( $_GET['nonce'] ) ? $_GET['nonce'] : '';
		$data_cat = isset( $_GET['data_cats'] ) ? $_GET['data_cats'] : '';
		$title = isset( $_GET['title'] ) ? $_GET['title'] : '';
		if ( ! wp_verify_nonce( $nonce, THEMESLUG . '_mega_menu' ) )
			die();
		
		if( !$data_cat )
			die();

		$output = '';
		$category_list = explode(',', $data_cat);

		global $post;

		$post_backup = $post;
		

		echo '<ul class="post-list post-list-with-thumbnail active row">';
			
			if( !empty( $category_list ) ): ?>
			<li class="sub-category-menu post-with-large-thumbnail col-md-3 col-lg-2">
				<ul class="sub-menu">
					<li data-cat="all" class="current loaded"><a href="#"><?php echo sprintf( _x( 'All %s', 'Sub menu item of Mews Mega menu ', 'yeahthemes' ), $title );?></a></li>
					<?php
					
					foreach ( $category_list as $cat_id ) {
						//print_r($this_cat);
						if( get_cat_name( $cat_id ) ):
						?>
							<li data-cat="<?php echo esc_attr( $cat_id );?>" class="loaded"><a href="<?php echo esc_attr( get_category_link( $cat_id ) );?>" title="<?php echo esc_attr( get_cat_name( $cat_id ) );?>"><?php echo get_cat_name( $cat_id );?></a></li>
						<?php
						endif;
					}
				?></ul>
			</li>
			<?php endif;

			$myposts = get_posts( apply_filters( 'yt_site_ajax_mega_menu_by_category_query', array( 
				'posts_per_page' => 5, 
				'cat' => $data_cat,
				) )
			);

			foreach ( $myposts as $post ) :
				setup_postdata( $post ); 

				static $count = 0;
				$count++;

				$post_cats = get_the_category(get_the_ID());
				$cat_tag_args = array();
				foreach ( $post_cats as $cat ) {
					if ( in_array( $cat->cat_ID, $category_list )) {
						$cat_tag_args['cat_ID'] = $cat->cat_ID;
						$cat_tag_args['name'] = $cat->name;
						$cat_tag_args['slug'] = $cat->slug;
						//echo 'Break';
						break;
					}
				}
				?>
				<li data-filter="all" style="<?php /*echo 'animation-delay:' . ($count * .1) .'s;-webkit-animation-delay:' . ($count* .1) .'s;';*/?>" class="post-with-large-thumbnail <?php echo 5 == $count || 4 == $count ? 'hidden-md ' : ''; ?>col-md-3 col-lg-2">
					<article <?php post_class();?>>
						<?php if ( has_post_thumbnail() && get_the_post_thumbnail() && ! post_password_required() ) : ?>
						<div class="post-thumb large">
							<span class="cat-tag <?php echo esc_attr($cat_tag_args['slug'] );?>"><?php echo $cat_tag_args['name'];?></span>
							<a href="<?php the_permalink(); ?>" rel="bookmark" title="<?php esc_attr( get_the_title() ); ?>"><?php the_post_thumbnail('medium'); ?></a>
						</div>
						<?php endif;?>
						
						<time class="entry-date published" datetime="<?php echo esc_attr( get_the_time('c') ); ?>"><?php the_time('M j, Y') ;?></time>
						<h3 class="secondary-2-primary no-margin-bottom"><a href="<?php the_permalink();?>" rel="bookmark"><?php the_title();?></a></h3>
						
					</article>
				</li>

				<?php

			endforeach;

			wp_reset_postdata();

			//Get the post from individual category 

			foreach ( $category_list as $cat_id ) :


				$myposts = get_posts( apply_filters( 'yt_site_ajax_sub_mega_menu_by_category_query', array( 
					'posts_per_page' => 5, 
					'cat' => $cat_id,
					) )
				);
				
				foreach ( $myposts as $post ) :
					setup_postdata( $post ); 

					static $count = 0;
					$count++;

					$post_cat = get_category( $cat_id );
					$cat_tag_args = array();

					$cat_tag_args['cat_ID'] = $post_cat->cat_ID;
					$cat_tag_args['name'] = $post_cat->name;
					$cat_tag_args['slug'] = $post_cat->slug;
					?>
					<li data-filter="<?php echo esc_attr( $cat_id );?>" style="display:none;" class="post-with-large-thumbnail <?php echo 5 == $count || 4 == $count ? 'hidden-md ' : ''; ?>col-md-3 col-lg-2">
						<article <?php post_class();?>>
							<?php if ( has_post_thumbnail() && get_the_post_thumbnail() && ! post_password_required() ) : ?>
							<div class="post-thumb large">
								<a href="<?php the_permalink(); ?>" rel="bookmark" title="<?php esc_attr( get_the_title() ); ?>"><?php the_post_thumbnail('medium'); ?></a>
							</div>
							<?php endif;?>
							
							<time class="entry-date published" datetime="<?php echo esc_attr( get_the_time('c') ); ?>"><?php the_time('M j, Y') ;?></time>
							<h3 class="secondary-2-primary no-margin-bottom"><a href="<?php the_permalink();?>" rel="bookmark"><?php the_title();?></a></h3>
							
						</article>
					</li>

					<?php

				endforeach;

				wp_reset_postdata();
			endforeach;
			//print_r(get_the_category(1));

		echo '</ul>';
		//print_r(get_the_category(1));
		
		$post = $post_backup;
		
		die(1);
    }
}

/**
 * Ajax News Mega menu
 *
 * @since 1.0.3
 */
if ( ! function_exists( 'yt_site_usual_mega_menu_by_category' ) ) {
	
	function yt_site_usual_mega_menu_by_category( $output, $mega_menu, $data_cat, $depth, $atts ){
		
		if( !$data_cat )
			return $output;

		if( $depth > 0 )
			return $output;

		if( empty( $mega_menu ) && 'news' !== $mega_menu )
			return $output;

		$output = '';
		$title = strip_tags( $atts['title'] );

	ob_start();

		$category_list = explode(',', $data_cat);

		global $post;

		$post_backup = $post;

		echo '<ul class="post-list post-list-with-thumbnail active row">';
			
			if( !empty( $category_list ) ): ?>
			<li class="sub-category-menu post-with-large-thumbnail col-md-3 col-lg-2">
				<ul class="sub-menu">
					<li data-cat="all" class="current loaded"><a href="#"><?php echo sprintf( _x( 'All %s', 'Sub menu item of Mews Mega menu ', 'yeahthemes' ), $title );?></a></li>
					<?php
					
					foreach ( $category_list as $cat_id ) {
						//print_r($this_cat);
						if( get_cat_name( $cat_id ) ):
						?>
							<li data-cat="<?php echo esc_attr( $cat_id );?>" class="loaded"><a href="<?php echo esc_attr( get_category_link( $cat_id ) );?>" title="<?php echo esc_attr( get_cat_name( $cat_id ) );?>"><?php echo get_cat_name( $cat_id );?></a></li>
						<?php
						endif;
					}
				?></ul>
			</li>
			<?php endif;

			$myposts = get_posts( apply_filters( 'yt_site_ajax_mega_menu_by_category_query', array( 
				'posts_per_page' => 5, 
				'cat' => $data_cat,
				) )
			);

			foreach ( $myposts as $post ) :
				setup_postdata( $post ); 

				static $count = 0;
				$count++;

				$post_cats = get_the_category(get_the_ID());
				$cat_tag_args = array();
				foreach ( $post_cats as $cat ) {
					if ( in_array( $cat->cat_ID, $category_list )) {
						$cat_tag_args['cat_ID'] = $cat->cat_ID;
						$cat_tag_args['name'] = $cat->name;
						$cat_tag_args['slug'] = $cat->slug;
						//echo 'Break';
						break;
					}
				}
				?>
				<li data-filter="all" style="<?php /*echo 'animation-delay:' . ($count * .1) .'s;-webkit-animation-delay:' . ($count* .1) .'s;';*/?>" class="post-with-large-thumbnail <?php echo 5 == $count || 4 == $count ? 'hidden-md ' : ''; ?>col-md-3 col-lg-2">
					<article <?php post_class();?>>
						<?php if ( has_post_thumbnail() && get_the_post_thumbnail() && ! post_password_required() ) : ?>
						<div class="post-thumb large">
							<span class="cat-tag <?php echo esc_attr($cat_tag_args['slug'] );?>"><?php echo $cat_tag_args['name'];?></span>
							<a href="<?php the_permalink(); ?>" rel="bookmark" title="<?php esc_attr( get_the_title() ); ?>"><?php the_post_thumbnail('medium'); ?></a>
						</div>
						<?php endif;?>
						
						<time class="entry-date published" datetime="<?php echo esc_attr( get_the_time('c') ); ?>"><?php the_time('M j, Y') ;?></time>
						<h3 class="secondary-2-primary no-margin-bottom"><a href="<?php the_permalink();?>" rel="bookmark"><?php the_title();?></a></h3>
						
					</article>
				</li>

				<?php

			endforeach;

			wp_reset_postdata();

			//Get the post from individual category 

			foreach ( $category_list as $cat_id ) :

				$myposts = get_posts( apply_filters( 'yt_site_ajax_sub_mega_menu_by_category_query', array( 
					'posts_per_page' => 5, 
					'cat' => $cat_id,
					) )
				);

				
				foreach ( $myposts as $post ) :
					setup_postdata( $post ); 

					static $count = 0;
					$count++;

					$post_cat = get_category( $cat_id );
					$cat_tag_args = array();

					$cat_tag_args['cat_ID'] = $post_cat->cat_ID;
					$cat_tag_args['name'] = $post_cat->name;
					$cat_tag_args['slug'] = $post_cat->slug;
					?>
					<li data-filter="<?php echo esc_attr( $cat_id );?>" style="display:none;" class="post-with-large-thumbnail <?php echo 5 == $count || 4 == $count ? 'hidden-md ' : ''; ?>col-md-3 col-lg-2">
						<article <?php post_class();?>>
							<?php if ( has_post_thumbnail() && get_the_post_thumbnail() && ! post_password_required() ) : ?>
							<div class="post-thumb large">
								<a href="<?php the_permalink(); ?>" rel="bookmark" title="<?php esc_attr( get_the_title() ); ?>"><?php the_post_thumbnail('medium'); ?></a>
							</div>
							<?php endif;?>
							
							<time class="entry-date published" datetime="<?php echo esc_attr( get_the_time('c') ); ?>"><?php the_time('M j, Y') ;?></time>
							<h3 class="secondary-2-primary no-margin-bottom"><a href="<?php the_permalink();?>" rel="bookmark"><?php the_title();?></a></h3>
							
						</article>
					</li>

					<?php

				endforeach;

				wp_reset_postdata();
			endforeach;
			//print_r(get_the_category(1));

		echo '</ul>';
		//print_r(get_the_category(1));
		
		$post = $post_backup;


				
		$content = ob_get_contents();
		
	ob_end_clean();

		$output .= $content;
		
		return $output;
    }
}

/**
 * Ajax News Sub
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_ajax_sub_mega_menu_by_category' ) ) {
	
	function yt_site_ajax_sub_mega_menu_by_category( ){

		$nonce = isset( $_GET['nonce'] ) ? $_GET['nonce'] : '';
		$data_cat = isset( $_GET['data_cat'] ) ? $_GET['data_cat'] : '';
		if ( ! wp_verify_nonce( $nonce, THEMESLUG . '_mega_menu' ) )
			die();
		
		if( !$data_cat )
			die();

		$output = '';

		global $post;

		$post_backup = $post;

		$myposts = get_posts( apply_filters( 'yt_site_ajax_sub_mega_menu_by_category_query', array( 
			'posts_per_page' => 5, 
			'cat' => $data_cat,
			) )
		);

		
		foreach ( $myposts as $post ) :
			setup_postdata( $post ); 

			static $count = 0;
			$count++;

			$post_cat = get_category( $data_cat );
			$cat_tag_args = array();

			$cat_tag_args['cat_ID'] = $post_cat->cat_ID;
			$cat_tag_args['name'] = $post_cat->name;
			$cat_tag_args['slug'] = $post_cat->slug;
			?>
			<li data-filter="<?php echo esc_attr( $data_cat );?>" style="<?php /*echo 'animation-delay:' . ($count * .1) .'s;-webkit-animation-delay:' . ($count* .1) .'s;';*/?>" class="post-with-large-thumbnail <?php echo 5 == $count || 4 == $count ? 'hidden-md ' : ''; ?>col-md-3 col-lg-2">
				<article <?php post_class();?>>
					<?php if ( has_post_thumbnail() && get_the_post_thumbnail() && ! post_password_required() ) : ?>
					<div class="post-thumb large">
						<span class="cat-tag <?php echo esc_attr($cat_tag_args['slug'] );?>"><?php echo $cat_tag_args['name'];?></span>
						<a href="<?php the_permalink(); ?>" rel="bookmark" title="<?php esc_attr( get_the_title() ); ?>"><?php the_post_thumbnail('medium'); ?></a>
					</div>
					<?php endif;?>
					
					<time class="entry-date published" datetime="<?php echo esc_attr( get_the_time('c') ); ?>"><?php the_time('M j, Y') ;?></time>
					<h3 class="secondary-2-primary no-margin-bottom"><a href="<?php the_permalink();?>" rel="bookmark"><?php the_title();?></a></h3>
					
				</article>
			</li>

			<?php

		endforeach;
		//print_r(get_the_category(1));
		wp_reset_postdata();
		
		$post = $post_backup;
		
		die(1);
    }
}

/**
 * Ajax Mobile Menu
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_mobile_nav' ) ) {
	 
	function yt_site_mobile_nav(){
		
		//Navnav
		if ( has_nav_menu( 'mobile' ) ) {
			$mobile_menu = wp_nav_menu(
				apply_filters( 'yt_site_mobile_navigation_args', array( 
					'theme_location' => 'mobile' , 
					'echo' => false, 
					'container_class' => 'site-mobile-navigation-menu-container',
					'menu_class'      => 'menu',
					'depth' => 2,
					'walker' => ''
				))
			);
		}else{
			$mobile_menu = '<ul class="menu"><li>' . sprintf( __('Create a Menu for small screen in <a href="%s">Menus</a> and assign it as Mobile Menu in <a href="%s">Theme Location</a>', 'yeahthemes'), admin_url('nav-menus.php'), admin_url('nav-menus.php?action=locations') ) . '</li></ul>';
		}
		
		$site_navigaton = $mobile_menu ;
		
		//Allow editing site
		$site_navigaton = yt_apply_atomic( 'site_mobile_menu', $site_navigaton );
		
		echo $site_navigaton;
	}
}

if ( ! function_exists( 'yt_site_ajax_mobile_menu' ) ) {
	
	function yt_site_ajax_mobile_menu( ){
		$nonce = isset( $_GET['nonce'] ) ? $_GET['nonce'] : '';

		if ( ! wp_verify_nonce( $nonce, THEMESLUG . '_mobile_menu' ) )
			die();

		yt_site_mobile_nav();
		die(1);
	}
}
/**
 * Site social network
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_social_networks' ) ) {
	 
	function yt_site_social_networks( $return = true){
		
		$yt_data = yt_get_options();

		$network_array = apply_filters( 'yt_site_social_networks_args', array( 
			'facebook' => __('Facebook', 'yeahthemes'), 
			'twitter' => __('Twitter', 'yeahthemes'), 
			'googleplus' => __('Google+', 'yeahthemes'), 
			'youtube' => __('Youtube', 'yeahthemes'), 
			'email' => __('Send an Email', 'yeahthemes'), 
			'rss' => __('RSS Feed', 'yeahthemes')
		) );

		$network_icon_array = apply_filters( 'yt_site_social_networks_icon_args', array( 
			'facebook' => 'fa fa-facebook', 
			'twitter' => 'fa fa-twitter', 
			'googleplus' => 'fa fa-google-plus', 
			'youtube' => 'fa fa-youtube', 
			'email' => 'fa fa-envelope', 
			'rss' => 'fa fa-rss', 
		) );
		
		$social_networks ='';

		foreach( $network_array as $network	 => $name ){

			if( !empty( $yt_data["scl_$network"] ) ){
				if( 'email' == $network ){
					$value = 'mailto:' . antispambot( $yt_data["scl_$network"] );
				}else{
					$value = esc_url( $yt_data["scl_$network"] );
				}
				$social_networks .= sprintf('<a href="%s" target="_blank" title="%s"><i class="%s"></i></a>',
					$value  ,
					$name,
					esc_attr( $network_icon_array[$network] )
				);
			}
		}

		if( $return  )
			return $social_networks;
		else
			echo $social_networks;
	}
}

/**
 * Archive header
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_archive_header' ) ) {
	
	function yt_site_archive_header(){
		if(!is_archive())
			return;

		if( yt_is_woocommerce() )
			return;

		if( yt_is_bbpress() )
			return;
		
		?>
		<header class="page-header archive-title hidden-print">
			<h1 class="page-title">
				<?php
					if ( is_category() ) :
						single_cat_title();

					elseif ( is_tag() ) :
						_e('Tag: ', 'framework');
						single_tag_title();

					elseif ( is_author() ) :
						/* Queue the first post, that way we know
						 * what author we're dealing with (if that is the case).
						*/
						the_post();
						printf( __( 'Author: %s', 'yeahthemes' ), '<span class="vcard"><a class="url fn n" href="' . esc_url( get_author_posts_url( get_the_author_meta( 'ID' ) ) ) . '" title="' . esc_attr( get_the_author() ) . '" rel="me">' . get_the_author() . '</a></span>' );
						/* Since we called the_post() above, we need to
						 * rewind the loop back to the beginning that way
						 * we can run the loop properly, in full.
						 */
						rewind_posts();

					elseif ( is_day() ) :
						printf( __( 'Day: %s', 'yeahthemes' ), '<span>' . get_the_date() . '</span>' );

					elseif ( is_month() ) :
						printf( __( 'Month: %s', 'yeahthemes' ), '<span>' . get_the_date( 'F Y' ) . '</span>' );

					elseif ( is_year() ) :
						printf( __( 'Year: %s', 'yeahthemes' ), '<span>' . get_the_date( 'Y' ) . '</span>' );

					elseif ( is_tax( 'post_format', 'post-format-aside' ) ) :
						_e( 'Asides', 'yeahthemes' );

					elseif ( is_tax( 'post_format', 'post-format-image' ) ) :
						_e( 'Images', 'yeahthemes');

					elseif ( is_tax( 'post_format', 'post-format-video' ) ) :
						_e( 'Videos', 'yeahthemes' );

					elseif ( is_tax( 'post_format', 'post-format-quote' ) ) :
						_e( 'Quotes', 'yeahthemes' );

					elseif ( is_tax( 'post_format', 'post-format-link' ) ) :
						_e( 'Links', 'yeahthemes' );

					else :
						_e( 'Archives', 'yeahthemes' );

					endif;
				?>
			</h1>
		<?php
		
			// Show an optional term description.
			$term_description = term_description();
			if ( ! empty( $term_description ) ) :
				printf( '<div class="taxonomy-description">%s</div>', $term_description );
			endif;
			
			
			if( is_category()){
				$category = get_category( get_query_var( 'cat' ) );
					$cat_id = $category->cat_ID;
				$args = array(
					'hierarchical' => 0,
					'child_of' => $cat_id,
					'title_li' => '',
					'show_option_none' => ''
				);
				$children = get_categories(array('child_of' => $cat_id,'hide_empty' => 0));
				if (count($children) > 1){
					echo '<ul class="list-inline descendants-cats">';
					wp_list_categories( $args );
					echo '</ul>';
				//has childern
				}

			}elseif( is_author( )){
				if(get_the_author_meta('description')){
					echo '<a href="'; the_author_meta('user_url'); echo '" class="alignleft gravatar">',get_avatar( get_the_author_meta('user_email'), '75', '' ),'</a>';
					echo wpautop( get_the_author_meta('description') );
					
				}
			}
		?>
		</header><!-- .page-header -->
<?php
	}
}
/**
 * Brick layout
 *
 * @since 1.0
 */ 

function yt_site_hero_banner(){
	yt_site_featured_news();
}

function yt_site_hero_banner_ids(){
	return yt_site_featured_news( 'ids' );
}

if ( ! function_exists( 'yt_site_featured_news' ) ) {
	
	function yt_site_featured_news( $output_data = 'html' ){

		if( !is_page() && !is_home() && !is_front_page() && !yt_is_woocommerce() )
			return;

		$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;

		global $post;
		/*Backup global post*/
		$backup_post = $post;

		$post_id = !empty( $post->ID ) ? $post->ID : 0;

		if( is_home() ){
			$post_id = get_option( 'page_for_posts' );
		}

		if( yt_is_woocommerce() && is_shop() && wc_get_page_id('shop') )
			$post_id = wc_get_page_id('shop');

		/*Allow filtering to show site hero on paged page for post*/
		if( is_paged() && !apply_filters( 'yt_site_hero_banner_allow_on_paged', false, $post_id ) ){
			return;
		}

		$hero_mode = get_post_meta( $post_id, 'yt_page_herobanner_mode', true  );
		
		if( !$hero_mode )
			return;

		$hero_layout 	= get_post_meta( $post_id, 'yt_page_herobanner_layout', true );
		$hero_style 	= get_post_meta( $post_id, 'yt_page_herobanner_style', true );
		$hero_effect	= get_post_meta( $post_id, 'yt_page_herobanner_effect', true );
		$hero_style_random = get_post_meta( $post_id, 'yt_page_herobanner_style_random', true );
		$categoryin 	= get_post_meta( $post_id, 'yt_page_herobanner_category', true  );
		$order 			= get_post_meta( $post_id, 'yt_page_herobanner_order', true );
		$orderby 		= get_post_meta( $post_id, 'yt_page_herobanner_orderby', true );
		$postsperpage 	= get_post_meta( $post_id, 'yt_page_herobanner_postsperpage', true );
		$postin 		= get_post_meta( $post_id, 'yt_page_herobanner_postin', true );
		$tagin 			= get_post_meta( $post_id, 'yt_page_herobanner_tagin', true );
		$exclude_format	= get_post_meta( $post_id, 'yt_page_herobanner_excludeformat', true );

		/*Asign post number*/ 
		$postsperpage = !empty( $postsperpage  ) && $postsperpage > 4 ? $postsperpage  : 8;

		if( 'default' == $hero_layout ){
			$postsperpage = 5;
		}
		elseif( 'symmetry_brick' == $hero_layout ){
			$postsperpage = 6;
		}

		/*Class style*/
		$hero_class = $hero_layout;
		if( 'color' == $hero_style ){
			$hero_class .= ' style-color-gradient';
		}elseif( 'mixed' == $hero_style ){
			$hero_class .= ' style-mixed-color-gradient';
		}
		/*overlay color*/
		$overlay_color = array( 
			'shamrock-skyblue', 
			'cerise-yellow',
			'yellow-skyblue',
			'shamrock-yellow',
			'waikawagray-cerise',
			'pictonblue-purple'
		);
		/*If is randon , do shuffling an array*/
		if( 'mixed' == $hero_style && $hero_style_random ){			
			shuffle( $overlay_color );
		}

		/*Begin query*/ 
		$hero_brick_query_args = array(
			'order' 			=> $order ? $order : 'DESC',
			'orderby' 			=> $orderby ? $orderby : 'date',
			'posts_per_page' 	=> intval( $postsperpage ),
			'post_type' 		=> 'post',
			'post_status' 		=> 'publish',
			'ignore_sticky_posts' => 1,
		);

		/* Push category to query*/
		if( !empty( $categoryin ) && is_array( $categoryin ) )
			$hero_brick_query_args['cat'] = join( ',', $categoryin );

		/* Push Specified post to query*/
		if( !empty( $postin ) && is_array( $postin ) )
			$hero_brick_query_args['post__in'] = $postin;

		/* Push Specified post to query*/
		if( !empty( $tagin ) && is_array( $tagin ) )
			$hero_brick_query_args['tag__in'] = $tagin;

		/* Push Specified post to query*/
		if( !empty( $exclude_format ) && is_array( $exclude_format ) ){
			$exclude_format_temp = array();
			foreach( $exclude_format as $format ){
				$exclude_format_temp[] = "post-format-$format";
			}

			$hero_brick_query_args['tax_query'] = array(
			    array(
			      'taxonomy' 	=> 'post_format',
			      'field' 		=> 'slug',
			      'terms' 		=> $exclude_format_temp,
			      'operator' 	=> 'NOT IN'
			    )
			);
		}
		/*Allow ordering posts by post views*/ 
		if( 'meta_value_num' == $orderby ){
			$hero_brick_query_args['meta_key'] = apply_filters( 'yt_simple_post_views_tracker_meta_key', '_post_views' );
			$hero_brick_query_args['meta_value_num'] = '0';
			$hero_brick_query_args['meta_compare'] = '>';
		}

		$slider_settings = apply_filters( 'yt_site_hero_banner_carousel_settings', array(
			'selector' => '.slides > li',
			//'directionNav' => false,
			'randomize' => 'true',
			'pausePlay' => false,
			'animationLoop' => false
		) , 'carousel' );


		$hero_post_ids = array();
		
		// print_r($x);
		// die();
		//$hero_query->post_count)

		//print_r($hero_brick_query_args); die();

		/*Init the query, and allow filtering*/
	/*If html == $output_data*/
	if( $output_data == 'html' ):

		$hero_query = new WP_Query( apply_filters( 'yt_site_hero_banner_query', $hero_brick_query_args, $post_id ) );

		if ( $hero_query->have_posts() && $hero_query->post_count >= $postsperpage ) {
			/*Begin site hero*/ 
			echo '<div id="site-hero" class="site-hero ' . esc_attr( $hero_class ) . ' border-bottom clearfix hidden-print yt-loading fadeIn animated" data-layout="'.esc_attr( $hero_layout ).'" data-style="'.esc_attr( $hero_style ).'" data-effect="'.esc_attr( $hero_effect ).'">
				<div class="container">
					<div class="row">';
				/*Slider wrapper for carousel*/
				if( 'carousel' == $hero_layout ){
					echo '<div class="yeahslider" data-settings="' . esc_attr( json_encode( $slider_settings ) ) . '">
						<ul class="slides">';
				}
			$count = 0;
			/*Start the Loop*/ 
			while ( $hero_query->have_posts() ) {
				$hero_query->the_post();
				$count++;
				/*Push the id to array*/
				$hero_post_ids[] = $hero_query->post->ID;

				if( $count > $postsperpage )
					break;

				$class 				= '';
				$thumb_size 		= 'medium';
				$thumb_holder_size 	= '320x190';
				$categories 		= get_the_category();
				$cat_tag 			= '';
				$column_size		= 'col-md-6 ';

				
				if( ( 1 == $count && 'default' == $hero_layout ) || ( in_array( $count, array( 1, 6 ) ) && 'symmetry_brick' == $hero_layout ) ){
					$class 			= ' hero-brick-large';
					$thumb_size 	= 'post-thumbnail';
					$thumb_holder_size = '670x410';
				}
				/*Category tag*/
				if( !empty( $categories[0] ) && apply_filters( 'yt_site_hero_element_cat', true, $post_id ) ){
					$category 	= $categories[0];
					$cat_tag  	.= '<span class="entry-category">';
					$cat_tag 	.= '<a class="cat-tag ' . esc_attr( $category->slug ) . '" href="'. esc_attr( get_category_link( $category->term_id ) ) .'" title="' . esc_attr( sprintf( __( 'View all posts in %s', 'yeahthemes' ), $category->name ) ) . '">'.$category->cat_name.'</a>';
					$cat_tag 	.= '</span>';
					//$class 		.= ' category-' . $category->slug;
				}
				/*Symmetric large brick*/
				if( in_array( $count, array( 1, 6 ) ) && 'symmetry_brick' == $hero_layout ){
					$column_size = 'col-md-12 ';
				}
				/*Carousel brick*/
				if( 'carousel' == $hero_layout ){
					$column_size = 'col-sm-6 col-md-3 ';
					if( 1 == $count )
						echo '<li>';
				}
				/*Symmetric & default layout*/
				if( in_array( $hero_layout, array( 'symmetry_brick', 'default' ) ) ){
					if( in_array( $count, array( 2, 3, 4, 5 ) ) )
						$column_size = 'col-sm-6 ' . $column_size;
					if( 6 == $count )
						$column_size = 'hidden-sm ' . $column_size;
				}

				$article_class = $column_size . 'hero-brick' . $class . ' clearfix visibility-hidden';

				if( ( 2 == $count && 'default' == $hero_layout ) || ( in_array( $count, array( 1, 4 ) ) && 'symmetry_brick' == $hero_layout ) ){
					echo '<div class="col-md-6">
					<div class="row">';
				}

					echo '<article class="' . esc_attr( join( ' ', get_post_class( $article_class ) ) ) . '">
						<header class="entry-header">
							' . $cat_tag . '
							<h2 class="entry-title"><a href="' . esc_url( get_permalink() ) . '" title="' . esc_attr( get_the_title() ) . '">' . get_the_title() . '</a></h2>
						</header>
						<div class="entry-content">
							<a href="' . esc_url( get_permalink() ) . '" class="entry-thumbnail' . ( 'mixed' == $hero_style ? esc_attr( ' goverlay-' . $overlay_color[ $count-1 ] ) : '' ) . '">';
							if( !has_post_thumbnail())
								echo '<img src="data:image/gif;base64,R0lGODdhQAG+AIAAAPr6+vr6+iwAAAAAQAG+AAAC/oSPqcvtD6OctNqLs968+w+G4kiW5omm6sq27gvH8kzX9o3n+s73/g8MCofEovGITCqXzKbzCY1Kp9Sq9YrNarfcrvcLDovH5LL5jE6r1+y2+w2Py+f0uv2Oz+v3/L7/DxgoOEhYaHiImKi4yNjo+AgZKTlJWWl5iZmpucnZ6fkJGio6SlpqeoqaqrrK2ur6ChsrO0tba3uLm6u7y9vr+wscLDxMXGx8jJysvMzc7PwMHS09TV1tfY2drb3N3e39DR4uPk5ebn6Onq6+jhtQ4T4RAD8jP+8gT4FvXM//wF/v75+Mfg3+AbwncJjBgwsW6mu48IXBgg7tJXAojCAA/o0INHI8QPAjiogMGG58ePGgyF0mT1p0abGlAZMyS1QsiXJmTp32auraWROo0Jc+Raj0KTPpUGQrIeZU+jJFU6gKqB4rWnVpyqhOt1pYKfKj1X07KRLVGpBhwnhBocZESwzr1rN0I6xdK2EqXJ5ZufKaaNdtX79e+X5Fujes3HZNB9N9zNbdYpxlYXZsqbgyy8ZznULOi2+yZ7Pw8FruXGyx3qGEHWdoXPHzZc2+sMIWHJl2WsI3Uc9u/VczZ5d9DwNHqPt318Jk/Q4fC1r06OiUi19tmxx6YOmDo3PVrrDscMOz84VOTvk48erMg9e1DgE88vXGj9ve+xMz68jlvvmTN5+dXDShR4tH4hHIU2ncqYWgcmnFd1SDsvQ2F4W/jZfgW5PFxh6EgGX04YUWipibhuhxCN923LWz24gp1edbi6aBpN5l7NyIY4467shjjz7+CGSQQg5JZJFGHolkkkouyWSTTj4JZZRSTklllVZeiWWWWm7JZZdefglmmGKOSWaZZp6JZppqrslmm26+CWeccs5JZ5123olnnnruyWeffv4JaKCCDkpooYYeimiiii7KaKOOPgpppJKyUgAAOw==">';
							else{
								
								the_post_thumbnail( $thumb_size );
							}
							echo '</a>
						</div>
						<footer class="entry-meta">
							<span class="pull-left posted-on"><i class="fa fa-clock-o"></i> <time class="entry-date published" datetime="' . esc_attr( get_the_time('c') ) . '">' . get_the_time('M j, Y') . '</time></span>
							<span class="pull-right with-cmt"><i class="fa fa-comments"></i> ';
							
							comments_popup_link( __( '0', 'yeahthemes' ), __( '1', 'yeahthemes' ), __( '%', 'yeahthemes' ));
							
							echo '</span>
						</footer>
					</article>';

				if( ( 5 == $count && 'default' == $hero_layout ) || ( in_array( $count, array( 3, 6 ) ) && 'symmetry_brick' == $hero_layout ) ){
					echo '</div>
					</div>';
				}
				/*Carousel brick*/
				if( 'carousel' == $hero_layout ){
					
					if( 4 == $count ){
						echo '</li>';
						$count = 0;
					}
				}
			
			}/*End the loop*/

				/* End slider wrapper for Carousel */
				if( 'carousel' == $hero_layout ){
					echo '</ul>
						</div>';
				}

			/*End site hero*/ 
				echo '</div>
				</div>
			</div>';
		} else {
			// no posts found
			echo '<div id="site-hero" class="site-hero border-bottom clearfix hidden-print yt-loading fadeIn animated text-center"><h3>' . __('You need to add more than 5 posts so the hero banner can show blocks properly', 'yeahthemes') . '</h3></div>';
		}
		//print_r( $hero_post_ids);

	else:
		$hero_brick_query_args['fields'] = 'ids';
		$hero_post_ids = get_posts( $hero_brick_query_args );
		//print_r( $hero_post_ids);
	endif;

		wp_reset_postdata();
		$post = $backup_post;

	/*Return hero ids*/
	if( $output_data !== 'html' )
		return $hero_post_ids;

	}
}

/*---------------------------------------------------------------------------------------------------------*
 * Primary content
 *---------------------------------------------------------------------------------------------------------*/

/*
 * Start primary wrapper
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_start_single_row' ) ) {
	 
	function yt_site_start_single_row(){
		echo '
		<div class="container">
			<div class="row">';
	}
}

/*
 * End primary wrapper
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_end_single_row' ) ) {
	 
	function yt_site_end_single_row(){
		
		echo '</div>
		</div>';
	}
}

/**
 * Secondary content
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_secondary_content' ) ) {
	 
	function yt_site_secondary_content(){

		$general_layout = yt_get_options( 'layout' );
		$general_layout = $general_layout ? $general_layout : 'default';
		$conditional = is_page() || ( is_home() && get_option( 'page_for_posts' ) ) || ( yt_is_woocommerce() && wc_get_page_id('shop') ) ;

		/* If is page OR is page for posts ( must set the page for posts in Reading)*/
		if( apply_filters( 'yt_site_secondary_content_conditional', $conditional ) ){
			if( !empty( $GLOBALS['post'] )){
				$post = $GLOBALS['post'];
				$post_id = $post->ID;
			}else{
				$post_id = 0;
			}

			if( is_home() && get_option( 'page_for_posts' ) )
				$post_id = get_option( 'page_for_posts' );

			if( yt_is_woocommerce() && wc_get_page_id('shop') )
				$post_id = wc_get_page_id('shop');

			$post_id = apply_filters( 'yt_site_secondary_content_post_id', $post_id );

			/*Retrieve page layout from meta key*/ 
			$page_layout = get_post_meta( $post_id, 'yt_page_sidebar_layout', true );

			/*Only display secondary sidebar on*/
			if( 'fullwidth' !== $page_layout )
				get_sidebar();
		}else{
			if( 'fullwidth' !== apply_filters( 'yt_site_secondary_content_general_layout', $general_layout ) )
				get_sidebar();
		}
		
	}
}

/**
 * Tertiary content
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_tertiary_content' ) ) {
	 
	function yt_site_tertiary_content(){

		$general_layout = yt_get_options( 'layout' );
		$general_layout = $general_layout ? $general_layout : 'default';
		$conditional = is_page() || ( is_home() && get_option( 'page_for_posts' ) ) || ( yt_is_woocommerce() && wc_get_page_id('shop') ) ;

		/* If is page OR is page for posts ( must set the page for posts in Reading)*/
		if( apply_filters( 'yt_site_tertiary_content_conditional', $conditional ) ){
			if( !empty( $GLOBALS['post'] )){
				$post = $GLOBALS['post'];
				$post_id = $post->ID;
			}else{
				$post_id = 0;
			}
			
			if( is_home() && get_option( 'page_for_posts' ) )
				$post_id = get_option( 'page_for_posts' );

			if( yt_is_woocommerce() && wc_get_page_id('shop') )
				$post_id = wc_get_page_id('shop');

			$post_id = apply_filters( 'yt_site_tertiary_content_post_id', $post_id );

			/*Retrieve page layout from meta key*/ 
			$page_layout = get_post_meta( $post_id, 'yt_page_sidebar_layout', true );
			
			if( !$page_layout )
				$page_layout = $general_layout;

			/*Only display secondary sidebar on*/
			if( in_array( $page_layout, array( 'default', 'double-sidebars' ) ) )
				get_sidebar( 'secondary' );
		}else{
			if( in_array( apply_filters( 'yt_site_tertiary_content_general_layout', $general_layout ), array( 'default', 'double-sidebars' ) ) )
				get_sidebar( 'secondary' );
		}
		
	}
}

//add_action( 'yt_tertiary_start','yt_ajax_posts_by_cat', 1);
if ( ! function_exists( 'yt_ajax_posts_by_cat' ) ) {
	 
	function yt_ajax_posts_by_cat(){
		?>
		
		<aside id="yt-ajax-posts-by-cat" class="widget yt-ajax-posts-by-cat yt-tabby-tabs yt-sliding-tabs collapsed-header">
			<div class="yt-tabby-tabs-header yt-sliding-tabs-header slashes-navigation widget-title smooth-scroller swiper-container">
				<ul class="swiper-wrapper">
					<li class="swiper-slide"><a href="#">All</a></li>
					<li class="swiper-slide"><a href="#">Technology</a></li>
					<li class="swiper-slide "><a href="#">WordPress</a>
						<ul>
							<li><a href="#">Themes</a></li>
							<li><a href="#">Plugins</a></li>
							<li><a href="#">Tutorial</a></li>
							<li><a href="#">Essentials</a></li>
						</ul>
					</li>
					<li class="swiper-slide"><a href="#">Design</a></li>
					<li class="swiper-slide"><a href="#">Business</a></li>
					<li class="swiper-slide active"><a href="#">Life/Living</a></li>
					<li class="swiper-slide"><a href="#">Entertaiment</a></li>
				</ul>
			</div>
			<span class="yt-sliding-tabs-header-trigger" data-action="expand"><span></span></span>
			<div class="yt-tabby-tabs-content yt-sliding-tabs-content">
				<ul class="post-list post-list-with-thumbnail vertical active">
					<li>
						<article>
							<time class="entry-date published" datetime="2013-11-24T19:03:05+00:00">November 24, 2013</time>
							<div class="post-thumb">
								<a href="#"><img src="http://placehold.it/60x60/EEE/555"></a>
							</div>
							<a href="#" rel="bookmark">
								<strong>Converting Our Stories Into Multi-Screen Experiences</strong>
							</a>
						</article>
					</li>
					<li>
						<article>
							<time class="entry-date published" datetime="2013-11-24T19:03:05+00:00">November 24, 2013</time>
							<div class="post-thumb">
								<a href="#"><img src="http://placehold.it/60x60/EEE/555"></a>
							</div>
							<a href="#" rel="bookmark">
								<strong>Simplify Mobile App Data With Google Analytics And Tag Manager</strong>
							</a>
						</article>
					</li>
					<li>
						<article>
							<time class="entry-date published" datetime="2013-11-24T19:03:05+00:00">November 24, 2013</time>
							<div class="post-thumb">
								<a href="#"><img src="http://placehold.it/60x60/EEE/555"></a>
							</div>
							<a href="#" rel="bookmark">
								<strong>“Be Humble, Be Honest, Don’t Be Afraid To Fail”</strong>
							</a>
						</article>
					</li>
					<li>
						<article>
							<time class="entry-date published" datetime="2013-11-24T19:03:05+00:00">November 24, 2013</time>
							<div class="post-thumb">
								<a href="#"><img src="http://placehold.it/60x60/EEE/555"></a>
							</div>
							<a href="#" rel="bookmark">
								<strong>Vine Quietly Adds Verified Badges for High-Profile Users</strong>
							</a>
						</article>
					</li>
					<li>
						<article>
							<time class="entry-date published" datetime="2013-11-24T19:03:05+00:00">November 24, 2013</time>
							<div class="post-thumb">
								<a href="#"><img src="http://placehold.it/60x60/EEE/555"></a>
							</div>
							<a href="#" rel="bookmark">
								<strong>Everything You've Always Wanted to Say to Your Facebook Friends</strong>
							</a>
						</article>
					</li>
					<li>
						<article>
							<time class="entry-date published" datetime="2013-11-24T19:03:05+00:00">November 24, 2013</time>
							<div class="post-thumb">
								<a href="#"><img src="http://placehold.it/60x60/EEE/555"></a>
							</div>
							<a href="#" rel="bookmark">
								<strong>‘Star Trek’ Mobile App Kicks Off Super Bowl Campaign</strong>
							</a>
						</article>
					</li>
				
				</ul>
			</div>
		</aside>
		
		<?php
	}
}
//add_action( 'yt_secondary_start','yt_tabbed_news_widget', 1);

if ( ! function_exists( 'yt_tabbed_news_widget' ) ) {
	 
	function yt_tabbed_news_widget(){

		
		?>
		
		<aside id="yt-twitter-profile-widget-2" class="widget yt-twitter-profile-widget yt-widget"><h3 class="widget-title">My Profile</h3>	    <div class="yt-twitter-profile-wrapper">
	    	<div class="yt-twitter-profile-header">
	            <a href="https://twitter.com/Yeahthemes" title=""><img width="48" height="48" src="http://pbs.twimg.com/profile_images/3543392032/b6e3e9273e2aab5d72bde038789c3647.jpeg" alt="Yeahthemes"></a>
	            <h4>Yeahthemes</h4>
	            <a href="https://twitter.com/Yeahthemes" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @Yeahthemes</a>
	        </div>
	        <div class="yt-twitter-profile-body">Everything you need to create a trendy, uniquely beautiful website without any of coding knowledge.</div>
	        <div class="yt-twitter-profile-footer">
	            <span class="status-count"><strong>283</strong> Tweets</span>
	            <span class="friends-count"><strong>174</strong> Following</span>
	            <span class="followers-count"><strong>374</strong> Followers</span>
	        </div>
	    </div>
		</aside>
		
		<?php
	}
}

add_filter('wp_list_categories', 'yt_site_cat_count_span');

function yt_site_cat_count_span($links) {
	$links = str_replace( 
		array( '</a> (', ')' . "\n" .'</li>' ), 
		array( '</a> <span>(', ')</span></li>' ),
		$links
	);
	return $links;
}

/**
 * After single post content
 *
 * -Author since 1.0.1
 * -Post nav
 * -5 related article
 * -You Might Also Like
 * -Comment
 */

/**
 * Post nav
 *
 * @since 1.0
 */

function yt_site_single_post_author(){
	if( !is_singular( 'post' ) )
		return;

	if( 'hide' == yt_get_options( 'blog_single_post_author_meta') )
		return;

	echo '<!--Author Info-->
    <div class="post-author-area hidden-print margin-bottom-30">
        <a href="'; the_author_meta('user_url'); echo '" class="alignleft gravatar">',get_avatar( get_the_author_meta('user_email'), '75', '' ),'</a>
        <h3 class="secondary-2-primary">',__('By','framework'),' <a href="'; the_author_meta('user_url');echo '"><strong>'; the_author_meta('display_name'); echo '</strong></a></h3>';
        
			if(get_the_author_meta('description')){
				
				echo wpautop( get_the_author_meta('description') );
				
			}
        echo '<p>',__('View all articles by ','framework'),'<strong class="primary-2-secondary">'; the_author_posts_link(); echo '</strong></p>

        <div class="clear"></div>';
        
        // if($yeah_data['md_single_post_author_social_profiles'] == 'show'){
        
        // echo '<!--Author Social Profile-->
        // <div class="mds-social-networks">
        //     <ul class="grayscale inline circle medium light ">';
        //         /*Retrieve social profile link*/
        //         global $md_social_services_arr;
        //         foreach($md_social_services_arr as $k => $v){
        //             if(get_the_author_meta($k)){
                    
        //                 echo '<li><a href="', get_the_author_meta($k), '" title="', $v,'" target="_blank"><i class="micon-',$k,'"></i></a></li>';	
        //             }
        //         }
        //     echo '</ul>
        // </div>
        // <!--/Author Social Profile-->';
        
        // }
    echo '</div>
    
    <!--/Author Info-->';
}

if ( ! function_exists( 'yt_site_single_post_dir_nav' ) ) {
	function yt_site_single_post_dir_nav(){
		yt_direction_nav( 'nav-below' );
	}
}
/**
 * Single post
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_single_post_related_articles' ) ) {
	 
	function yt_site_single_post_related_articles(){

		if( !is_singular( 'post' ))
			return;

		if( 'hide' == yt_get_options( 'blog_single_post_related_articles') )
			return;

		global $post;

		$backup_post = $post;

		if( !empty( $post )){
			$post_id = $post->ID;
		}else{
			$post_id = 0;
		}

		$tags = wp_get_post_tags( $post_id );
		if ($tags):

			$tag_ids = array();  
			foreach( $tags as $tag )
				$tag_ids[] = $tag->term_id; 

			$args = array(  
				'tag__in' => $tag_ids,  
				'post__not_in' => array( $post_id ),  
				'posts_per_page'=> 5 //number of posts to display
			);       
			$related_articles = get_posts( apply_filters( 'yt_site_single_post_related_articles_query', $args, $post_id ) );
			if( $related_articles ):?>
			<div class="entry-stuff margin-bottom-30 related-articles hidden-print secondary-2-primary">
				<h3 class="related-articles-title"><?php _e( 'Related Articles', 'yeahthemes'); ?></h3>
				<ul class="list-unstyled list-with-separator">
				<?php
				foreach ( $related_articles as $post ) : 
	  				setup_postdata( $post ); ?>
					<li><a href="<?php the_permalink();?>"><i class="fa fa-file-text-o "></i> <?php echo  the_title();?> - <time class="entry-date published" datetime="<?php echo esc_attr( get_the_time('c') ); ?>"><?php echo the_time('M j, Y');?></time></a></li>
	  			<?php endforeach;?>

				</ul>
			</div>
	  		<?php
  			endif;
			wp_reset_postdata();
		endif;

		$post = $backup_post;
	}
}


/**
 * Single post
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_single_post_you_might_also_like' ) ) {
	 
	function yt_site_single_post_you_might_also_like(){

		global $post;

		$backup_post = $post;

		if( empty( $post ) && !is_single() )
			return;

		if( 'hide' == yt_get_options( 'blog_single_post_youmightalsolike') )
			return;

		/*Get current post's categories*/
		$post_cats_temp = get_the_category( $post->ID );
		$post_cats = array();
		if( !empty( $post_cats_temp )){
			foreach ( $post_cats_temp as $cat) {
				$post_cats[] = $cat->cat_ID;
			}
		}

		if( empty( $post_cats ) )
			return;


		global $wpdb;
		// $querystr = "
		// 	SELECT $wpdb->posts . * 
		// 	FROM $wpdb->posts, $wpdb->postmeta 
		// 	WHERE $wpdb->posts.ID = $wpdb->postmeta.post_id 
		// 	AND $wpdb->postmeta.meta_key = '_post_views' 
		// 	AND $wpdb->postmeta.meta_value > 1 
		// 	AND $wpdb->posts.post_status = 'publish' 
		// 	AND $wpdb->posts.post_type = 'post' 
		// 	ORDER BY $wpdb->postmeta.meta_value DESC LIMIT 4
		// ";

		// foreach ($wpdb->get_results(  $querystr ) as $key) {

		// 	echo "$key->post_title<br>";
			
		// }

		/*Prepare the query, allow modifying by applying filter*/
		$myposts = get_posts( apply_filters( 'yt_site_single_post_you_might_also_like_query', array( 
			'order' 			=> 'DESC',
			'orderby' 			=> 'title date',
			'post_type' 		=> 'post',
			'post_status' 		=> 'publish',
			'post__not_in'		=> array( $post->ID ),
			'posts_per_page' => 4, 
			'category__in' => $post_cats,
			'tax_query' => array(
				array(
					'taxonomy' 	=> 'post_format',
					'field' 	=> 'slug',
					'terms' 	=> array( 'post-format-image', 'post-format-link', 'post-format-quote'),
					'operator' 	=> 'NOT IN'
				)
			)
		) ) );

		if ( $myposts ) :
			echo '<div class="entry-stuff secondary-2-primary you-might-also-like-articles hidden-print margin-bottom-30">';
				echo sprintf( '<h3>%s</h3>', __( 'You Might Also Like', 'yeahthemes' ) );
				echo '<ul class="post-list post-list-with-thumbnail horizontal row">';
				foreach ( $myposts as $post ) :
					setup_postdata( $post );

					static $count = 0;
					$count++;

					$categories = get_the_category();
					$cat_tag 			= '';
			
					if( !empty( $categories[0] ) ){
						$category 	= $categories[0];
						$cat_tag 	.= '<span class="cat-tag ' . esc_attr( $category->slug ) . '">'.$category->cat_name.'</span>';
					}
					?>
					<li class="post-with-large-thumbnail col-xs-6 col-sm-6 col-md-4 margin-bottom-15<?php echo 4 == count( $myposts ) && 4 == $count ? ' hidden-md hidden-lg' : ''; ?>">
						<article <?php post_class();?>>
							<?php if( has_post_thumbnail() && get_the_post_thumbnail() && ! post_password_required() ): ?>
							<div class="post-thumb large">
								<?php echo $cat_tag;?>
								<a href="<?php the_permalink(); ?>" rel="bookmark" title="<?php esc_attr( get_the_title() ); ?>"><?php the_post_thumbnail('medium'); ?></a>
							</div>
							<?php endif;?>
							
							<time class="entry-date published" datetime="<?php echo esc_attr( get_the_time('c') ); ?>"><?php the_time('M j, Y');?></time>
							<h2><a href="<?php echo esc_attr( get_permalink() );?>" rel="bookmark"><?php the_title();?></a></h2>
							
						</article>
					</li>
					<?php

				endforeach;
				echo '</ul>';
			echo '</div>';
		endif;

		/*Reset post data & restore global post*/
		wp_reset_postdata();
		
		/*Restore post*/
		$post = $backup_post;
	}
}

/**
 * Post comment
 *
 * @since 1.0
 */	

if ( ! function_exists( 'yt_site_single_post_comment' ) ) {
	 
	function yt_site_single_post_comment(){
		// If comments are open or we have at least one comment, load up the comment template
		if ( 'show' == yt_get_options( 'blog_single_post_comment_template' ) && ( comments_open() || '0' != get_comments_number() ) )
			comments_template();
	}
}
/*---------------------------------------------------------------------------------------------------------*
 * Theme Footer
 *---------------------------------------------------------------------------------------------------------*/
if ( ! function_exists( 'yt_site_footer' ) ) {
	 
	function yt_site_footer(){
		$footer_layout = yt_get_options('footer_layout');

		if( 'footer-extra' !== $footer_layout ):
		?>
	 
	 	<div class="footer-widgets full-width-wrapper">
			<div class="container">
				<div class="row">
					<?php yt_theme_footer_sidebars();?>
				</div>
			</div><!-- .footer-widget -->
		</div>

		<?php endif;

		if( 'footer-widget' !== $footer_layout && ( yt_get_options('footer_text_left') || yt_get_options('footer_text_right')) ):?>

		<div class="site-info footer-info full-width-wrapper">
			<div class="container">
				<?php 
				if( yt_get_options('footer_text_left') ){
					echo sprintf( '<div class="pull-left text-left">%s</div>', yt_get_options('footer_text_left') );
				}
				if( yt_get_options('footer_text_right') ){
					echo sprintf( '<div class="pull-right text-right">%s</div>', yt_get_options('footer_text_right') );
				}
				
				?>
			</div>
		</div><!-- .site-info -->
		
		<?php
		endif;
	}
}


/*---------------------------------------------------------------------------------------------------------*
 * Theme ads
 *---------------------------------------------------------------------------------------------------------*/

/**
 * Head Ads
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_head_ads' ) ) {
	
	function yt_site_head_ads(){
		
		
		if( !empty( $GLOBALS['post'] )){
			$post = $GLOBALS['post'];
			$post_id = $post->ID;
		}else{
			$post_id = 0;
		}
		
		if( yt_get_options( 'site_ads_after_header' ) ):
			$output = sprintf('<div class="site-head-ads clearfix border-bottom">
				<div class="container site-head-ads text-center padding-top-30 padding-bottom-30 clearfix">
				%s
				</div>
			</div>', yt_get_options( 'site_ads_after_header' ));

			echo apply_filters( 'yt_site_head_ads', $output, $post_id );
		endif;
	}
}

/**
 * Foot Ads
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_foot_ads' ) ) {
	
	function yt_site_foot_ads(){

		if( !empty( $GLOBALS['post'] )){
			$post = $GLOBALS['post'];
			$post_id = $post->ID;
		}else{
			$post_id = 0;
		}

		if( yt_get_options( 'site_ads_before_footer' ) ):
			$output = sprintf('<div class="site-head-ads clearfix border-top">
				<div class="container site-head-ads text-center padding-top-30 padding-bottom-30 clearfix">
				%s
				</div>
			</div>', yt_get_options( 'site_ads_before_footer' ));
			echo apply_filters( 'yt_site_foot_ads', $output, $post_id );
		endif;
	}
}

/**
 * Single post ads
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_single_post_ads_750x90' ) ) {
	function yt_site_single_post_ads_750x90(){

		if( !is_singular( 'post' ))
			return;

		if( !empty( $GLOBALS['post'] )){
			$post = $GLOBALS['post'];
			$post_id = $post->ID;
		}else{
			$post_id = 0;
		}

		if( yt_get_options( 'site_ads_after_single_post' ) ):
			$output = '<div class="entry-stuff margin-bottom-30 hidden-print single-post-ads-750x90">';
			$output .= stripslashes( yt_get_options( 'site_ads_after_single_post' ) );
			$output .= '</div>';
			echo apply_filters( 'yt_site_single_post_ads_750x90', $output, $post_id );
		endif;
		
	}
}
 

 
/*---------------------------------------------------------------------------------------------------------*
 * Theme sections's classes
 * 
 * Adding classes for Sections
 *---------------------------------------------------------------------------------------------------------*/


/*
 * Primary Class
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_primary_class' ) ) {
	 
	function yt_site_primary_class($_classes){
		
		$theme_layouts = array(
			'default', 
			'right-sidebar',
			'left-sidebar',
			'fullwidth',
			'double-sidebars'
		);

		$general_layout = yt_get_options( 'layout' );
		$general_layout = in_array( $general_layout, $theme_layouts ) ? $general_layout : 'default';
		$page_layout = $general_layout;
		$conditional = is_page() || ( is_home() && get_option( 'page_for_posts' ) ) || ( yt_is_woocommerce() && wc_get_page_id('shop') ) ;
		
		/* If is page OR is page for posts ( must set the page for posts in Reading)*/
		if( apply_filters( 'yt_site_primary_class_conditional', $conditional ) ){
			if( !empty( $GLOBALS['post'] )){
				$post = $GLOBALS['post'];
				$post_id = $post->ID;
			}else{
				$post_id = 0;
			}
			
			if( is_home() && get_option( 'page_for_posts' ) )
				$post_id = get_option( 'page_for_posts' );

			if( yt_is_woocommerce() && wc_get_page_id('shop') ){
				$post_id = wc_get_page_id('shop');
			}

			/*Retrieve page layout from meta key*/ 
			$page_layout = get_post_meta( $post_id, 'yt_page_sidebar_layout', true );
			
			if( !$page_layout )
				$page_layout = $general_layout;
		}
		
		$page_layout = apply_filters( 'yt_site_page_layout_primary', $page_layout );

		$classes = array();

		if( 'default' == $page_layout ){

			$classes[] = 'col-sm-12';
			//$classes[] = 'col-sm-push-3';
			
			$classes[] = 'col-md-7';
			$classes[] = 'col-md-push-2';
			
			$classes[] = 'col-lg-7';
			$classes[] = 'col-lg-push-2';

			$classes[] = 'boundary-column';

		}elseif( 'double-sidebars' == $page_layout ){

			$classes[] = 'col-sm-12';
			$classes[] = 'col-md-6';

		}elseif( 'right-sidebar' == $page_layout ){

			$classes[] = 'col-sm-12';
			$classes[] = 'col-md-8';

		}elseif( 'left-sidebar' == $page_layout ){

			$classes[] = 'col-sm-12';
			$classes[] = 'col-md-8';
			$classes[] = 'col-md-push-4';

		}elseif( 'fullwidth' == $page_layout ){

			$classes[] = 'col-sm-12';
		}else{


			$classes = apply_filters( 'yt_site_primary_classes_custom_layout', $classes, $page_layout );
		}

		$classes[] = 'printable-section';
		//$classes[] = 'fadeIn animated';
		
		$classes = apply_filters( 'yt_site_primary_classes', $classes );
		
		$_classes = array_merge( $_classes, $classes );

		return $_classes;
	}
}

/*
 * Secondary Class
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_secondary_class' ) ) {
	 
	function yt_site_secondary_class($_classes){

		$theme_layouts = array(
			'default', 
			'right-sidebar',
			'left-sidebar',
			'fullwidth',
			'double-sidebars'
		);

		$general_layout = yt_get_options( 'layout' );
		$general_layout = in_array( $general_layout, $theme_layouts ) ? $general_layout : 'default';
		$page_layout = $general_layout;
		$conditional = is_page() || ( is_home() && get_option( 'page_for_posts' ) ) || ( yt_is_woocommerce() && wc_get_page_id('shop') ) ;
		
		/* If is page OR is page for posts ( must set the page for posts in Reading)*/
		if( apply_filters( 'yt_site_secondary_class_conditional', $conditional ) ){
			if( !empty( $GLOBALS['post'] )){
				$post = $GLOBALS['post'];
				$post_id = $post->ID;
			}else{
				$post_id = 0;
			}

			if( is_home() && get_option( 'page_for_posts' ) )
				$post_id = get_option( 'page_for_posts' );

			if( yt_is_woocommerce() && wc_get_page_id('shop') )
				$post_id = wc_get_page_id('shop');

			/*Retrieve page layout from meta key*/ 
			$page_layout = get_post_meta( $post_id, 'yt_page_sidebar_layout', true );
			
			if( !$page_layout )
				$page_layout = $general_layout;
		}

		$page_layout = apply_filters( 'yt_site_page_layout_secondary', $page_layout );

		$classes = array();

		if( 'default' == $page_layout ){
	
			$classes[] = 'hidden-xs';

			$classes[] = 'col-sm-3';
			$classes[] = 'col-sm-push-3';
			$classes[] = 'hidden-sm';
			
			$classes[] = 'col-md-3';
			$classes[] = 'col-md-push-2';
			
			$classes[] = 'col-lg-3';
			$classes[] = 'col-lg-push-2';

		}elseif( 'double-sidebars' == $page_layout ){

	
			$classes[] = 'hidden-xs';

			
			$classes[] = 'col-sm-3';
			$classes[] = 'col-sm-push-3';
			$classes[] = 'hidden-sm';
			
			$classes[] = 'col-md-3';
			$classes[] = 'col-md-push-3';
			
			$classes[] = 'col-lg-3';
			$classes[] = 'col-lg-push-3';

		}elseif( 'right-sidebar' == $page_layout ){

			$classes[] = 'hidden-xs';

			$classes[] = 'col-sm-12';
			$classes[] = 'hidden-sm';
			
			$classes[] = 'col-md-4';

		}elseif( 'left-sidebar' == $page_layout ){

			$classes[] = 'hidden-xs';

			$classes[] = 'col-sm-12';
			$classes[] = 'hidden-sm';

			$classes[] = 'col-md-4';
			$classes[] = 'col-md-pull-8';

		}else{
			$classes = apply_filters( 'yt_site_secondary_classes_custom_layout', $classes, $page_layout );
		}

		$classes[] = 'hidden-print';
		//$classes[] = 'fadeIn animated';
		
		$classes = apply_filters( 'yt_site_secondary_classes', $classes );
		
		$_classes = array_merge( $_classes, $classes );

		return $_classes;
	}
}
/*
 * Tertiary Class
 *
 * @since 1.0
 */

if ( ! function_exists( 'yt_site_tertiary_class' ) ) {
	 
	function yt_site_tertiary_class($_classes){

		$theme_layouts = array(
			'default', 
			'right-sidebar',
			'left-sidebar',
			'fullwidth',
			'double-sidebars'
		);

		$general_layout = yt_get_options( 'layout' );
		$general_layout = in_array( $general_layout, $theme_layouts ) ? $general_layout : 'default';
		$page_layout = $general_layout;		
		$conditional = is_page() || ( is_home() && get_option( 'page_for_posts' ) ) || ( yt_is_woocommerce() && wc_get_page_id('shop') ) ;
		
		/* If is page OR is page for posts ( must set the page for posts in Reading)*/
		if( apply_filters( 'yt_site_tertiary_class_conditional', $conditional ) ){
			if( !empty( $GLOBALS['post'] )){
				$post = $GLOBALS['post'];
				$post_id = $post->ID;
			}else{
				$post_id = 0;
			}
			
			if( is_home() && get_option( 'page_for_posts' ) )
				$post_id = get_option( 'page_for_posts' );

			if( yt_is_woocommerce() && wc_get_page_id('shop') )
				$post_id = wc_get_page_id('shop');

			/*Retrieve page layout from meta key*/ 
			$page_layout = get_post_meta( $post_id, 'yt_page_sidebar_layout', true );
			
			if( !$page_layout )
				$page_layout = $general_layout;
		}

		$page_layout = apply_filters( 'yt_site_page_layout_tertiary', $page_layout );
		$classes = array();
		if( 'default' == $page_layout ){

			$classes[] = 'hidden-xs';
			
			$classes[] = 'col-sm-3';
			$classes[] = 'col-sm-pull-9';
			$classes[] = 'hidden-sm';
			
			
			$classes[] = 'col-md-2';
			$classes[] = 'col-md-pull-10';
			
			$classes[] = 'col-lg-2';
			$classes[] = 'col-lg-pull-10';

		}elseif( 'double-sidebars' == $page_layout ){

			$classes[] = 'hidden-xs';
			
			$classes[] = 'col-sm-3';
			$classes[] = 'col-sm-pull-3';
			$classes[] = 'hidden-sm';
			
			
			$classes[] = 'col-md-3';	
			$classes[] = 'col-md-pull-3';
			
			$classes[] = 'col-lg-3';
			$classes[] = 'col-lg-pull-3';
			$classes[] = 'boundary-column';

		}else{

			$classes = apply_filters( 'yt_site_tertiary_classes_custom_layout', $classes, $page_layout );

		}
		
		$classes[] = 'hidden-print';
		//$classes[] = 'fadeIn animated';

		$classes = apply_filters( 'yt_site_tertiary_classes', $classes );

		$_classes = array_merge( $_classes, $classes );

		return $_classes;
	}
}
/*
 * Content Class
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_content_class' ) ) {
	 
	function yt_site_content_class($_classes){
		
		if( !is_home() && !is_page() )
			return $_classes;

		global $post;

		$post_id = $post->ID;

		if( is_home() && is_main_query() && get_option('page_for_posts' ) ){

			$post_id = $post->ID = get_option('page_for_posts' );
		}


		$layout = get_post_meta( $post_id, 'yt_page_queryposts_layout', true );
		$query_post_mode = get_post_meta( $post_id, 'yt_page_queryposts_mode', true); 

		if( $query_post_mode && $layout ){
			$_classes[] = "post-layout-$layout";
		}

			
		return $_classes;
	}
}

/*
 * Footer Class
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_footer_class' ) ) {
	 
	function yt_site_footer_class($_classes){

		$classes = array();
		
		$classes[] = 'full-width-wrapper';
		$classes[] = 'hidden-print';
		
		$classes = apply_filters( 'yt_site_footer_classes', $classes );
		
		$_classes = array_merge( $_classes, $classes );

		return $_classes;
	}
}

/*
 * Header Class
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_header_class' ) ) {
	 
	function yt_site_header_class($_classes){

		$classes = array();
		
		$classes[] = 'full-width-wrapper';

		$classes[] = 'hidden-print';
		
		$classes = apply_filters( 'yt_site_header_classes', $classes );
		
		$_classes = array_merge( $_classes, $classes );

		return $_classes;
	}
}

if ( ! function_exists( 'yt_site_wrapper_class' ) ) {
	 
	function yt_site_wrapper_class($classes){
		
		$classes[] = 'full-width-wrapper';
		
		return $classes;
	}
}

//add_filter( 'yt_wrapper_attribute','yt_site_wrapper_attr');

if ( ! function_exists( 'yt_site_wrapper_attr' ) ) {
	 
	function yt_site_wrapper_attr($attr){
		
		$attr .= ' data-general="hahahah"';
		
		return $attr;
	}
}

//add_filter( 'yt_home_wrapper_attribute','yt_site_home_wrapper_attr');

if ( ! function_exists( 'yt_site_home_wrapper_attr' ) ) {
	 
	function yt_site_home_wrapper_attr($attr){
		
		$attr .= ' data-home-wrapper=""';
		
		return $attr;
	}
}

/*
 * Overwrite Impressive like Plugin settings
 *
 * @since 1.0
 * @framework 1.0
 */

add_filter( 'yt_impressive_like_symbol', 'yt_site_impressive_like_symbol');

if( !function_exists( 'yt_site_impressive_like_symbol') ) {
	
	function yt_site_impressive_like_symbol(){
		return '<i class="fa fa-heart"></i>';
	}
}

add_filter( 'yt_icon_next_post', 'yt_site_icon_next_post');

if( !function_exists( 'yt_site_icon_next_post') ) {
	
	function yt_site_icon_next_post(){
		return '<i class="fa fa-chevron-right"></i>';
	}
}

add_filter( 'yt_icon_prev_post', 'yt_site_icon_prev_post');

if( !function_exists( 'yt_site_icon_prev_post') ) {
	
	function yt_site_icon_prev_post(){
		return '<i class="fa fa-chevron-left"></i>';
	}
}