<?php
// This file is not called from WordPress. We don't like that.
! defined( 'ABSPATH' ) and exit;

/**
 **********************************************************************************************************
 * 												DO NOT EDIT THIS FILE
 **********************************************************************************************************
 *
 *
 * Theme Init
 *
 * @author		Yeahthemes
 * @copyright	Copyright ( c ) Yeahthemes
 * @link		http://yeahthemes.com
 * @since		Version 1.0
 * @package 	Yeah Includes
 */
define( 'YEAHTHEMES_CINCLUDES_URI', get_template_directory_uri() . '/includes/' );
define( 'YEAHTHEMES_CINCLUDES_DIR', get_template_directory() . '/includes/' );
define( 'YEAHTHEMES_CINCLUDES_IMG_URI', YEAHTHEMES_CINCLUDES_URI . 'images/' );
define( 'YEAHTHEMES_CINCLUDES_CSS_URI', YEAHTHEMES_CINCLUDES_URI . 'css/' );
define( 'YEAHTHEMES_CINCLUDES_JS_URI', YEAHTHEMES_CINCLUDES_URI . 'js/' );

/**
 * Load functions
 *
 */

$yt_includes_includes  = apply_filters( 'yt_locate_template_includes_includes',
	array(
	
		'includes/theme-meta-boxes.php',
		'includes/theme-scripts.php',
		'includes/theme-shortcodes.php',
		'includes/theme-general-functions.php',
		'includes/theme-template-functions.php',
		'includes/theme-config.php',
		'includes/theme-functions.php',
		'includes/theme-interface.php',
		'includes/theme-styling.php',
		'includes/theme-wpml.php',
		'includes/theme-woocommerce.php',
		'includes/theme-bbpress.php',
		'includes/theme-widgets.php',
		'includes/theme-hooks.php'
	)
);
			
foreach ( $yt_includes_includes as $include ) { 
	locate_template( $include, true );
}